# Fake News Detection Using Python

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

### Importing data from the dataset
Dataset from Kaggle:
Link: <a href = "https://www.kaggle.com/datasets/hassanamin/textdb3?resource=download"> Click Me </a>

In [4]:
data = pd.read_csv('fake_or_real_news.csv')

In [6]:
print(data.head())

   Unnamed: 0                                              title  \
0        8476                       You Can Smell Hillary’s Fear   
1       10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2        3608        Kerry to go to Paris in gesture of sympathy   
3       10142  Bernie supporters on Twitter erupt in anger ag...   
4         875   The Battle of New York: Why This Primary Matters   

                                                text label  
0  Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1  Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2  U.S. Secretary of State John F. Kerry said Mon...  REAL  
3  — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4  It's primary day in New York and front-runners...  REAL  


In [9]:
data.shape

(6335, 4)

### Checking if there is any missing values

In [14]:
data.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

##### As there are no missing values then let us use the title column as the feature to train the model

In [22]:
x=np.array(data['title'])
y=np.array(data['label'])
Vectorizer = CountVectorizer()
x = Vectorizer.fit_transform(x)

In [30]:
feature_name = Vectorizer.get_feature_names_out()
print(feature_name)

['00' '000' '00pm' ... 'مطالعاتی' 'مورد' 'کدآمایی']


In [32]:
print(x.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [73]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=10)
model = MultinomialNB()
model.fit(X_train,Y_train)
model.score(X_test,Y_test)

0.8310970797158642

#### Testing the Trained Model

In [99]:
news = "2016 Republican race enters a new, volatile phase"
data = Vectorizer.transform(['news']).toarray()
print(data)

[[0 0 0 ... 0 0 0]]


In [97]:
print(model.predict(data))

['FAKE']


In [95]:
news_headline = "Cow dung can cure Corona Virus"
data = Vectorizer.transform([news_headline]).toarray()
print(model.predict(data))

['FAKE']


In [ ]:
print(model.f1_score)